import { cn } from "@/lib/utils";

const variants: Record<string, string> = {
  active: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  suspended: "bg-destructive/10 text-destructive border-destructive/20",
  live: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  upcoming: "bg-primary/10 text-primary border-primary/20",
  past: "bg-muted text-muted-foreground border-border",
  cancelled: "bg-destructive/10 text-destructive border-destructive/20",
  banned: "bg-destructive/10 text-destructive border-destructive/20",
  pending: "bg-amber-100 text-amber-700 border-amber-200",
  open: "bg-primary/10 text-primary border-primary/20",
  closed: "bg-muted text-muted-foreground border-border",
  archived: "bg-muted text-muted-foreground border-border",
  hidden: "bg-muted text-muted-foreground border-border",
  submitted: "bg-amber-100 text-amber-700 border-amber-200",
  private: "bg-amber-100 text-amber-700 border-amber-200",
  public: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  reviewing: "bg-amber-100 text-amber-700 border-amber-200",
  resolved: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  dismissed: "bg-muted text-muted-foreground border-border",
  free: "bg-muted text-muted-foreground border-border",
  paid: "bg-primary/10 text-primary border-primary/20",
  unknown: "bg-amber-100 text-amber-700 border-amber-200",
  plus: "bg-primary/10 text-primary border-primary/20",
  afterdark: "bg-purple-100 text-purple-700 border-purple-200",
  trial: "bg-amber-100 text-amber-700 border-amber-200",
  expired: "bg-muted text-muted-foreground border-border",
  succeeded: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  refunded: "bg-amber-100 text-amber-700 border-amber-200",
  failed: "bg-destructive/10 text-destructive border-destructive/20",
  published: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  draft: "bg-muted text-muted-foreground border-border",
  rejected: "bg-destructive/10 text-destructive border-destructive/20",
  high: "bg-destructive/10 text-destructive border-destructive/20",
  med: "bg-amber-100 text-amber-700 border-amber-200",
  low: "bg-muted text-muted-foreground border-border",
  meetup: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  date: "bg-pink-100 text-pink-700 border-pink-200",
  subscription: "bg-primary/10 text-primary border-primary/20",
  "one-time": "bg-muted text-muted-foreground border-border",
  sent: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  scheduled: "bg-primary/10 text-primary border-primary/20",
  sending: "bg-amber-100 text-amber-700 border-amber-200",
  queue: "bg-amber-100 text-amber-700 border-amber-200",
  approved: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  needs_info: "bg-amber-100 text-amber-700 border-amber-200",
  paused: "bg-muted text-muted-foreground border-border",
  ended: "bg-muted text-muted-foreground border-border",
  policy: "bg-primary/10 text-primary border-primary/20",
  faq: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  rules: "bg-amber-100 text-amber-700 border-amber-200",
  onboarding: "bg-pink-100 text-pink-700 border-pink-200",
  page: "bg-muted text-muted-foreground border-border",
  push: "bg-primary/10 text-primary border-primary/20",
  email: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  inapp: "bg-pink-100 text-pink-700 border-pink-200",
  selfie: "bg-primary/10 text-primary border-primary/20",
  document: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  photo: "bg-pink-100 text-pink-700 border-pink-200",
  discount: "bg-primary/10 text-primary border-primary/20",
  credit: "bg-secondary/15 text-secondary-foreground border-secondary/30",
  community: "bg-purple-100 text-purple-700 border-purple-200",
  poster: "bg-amber-100 text-amber-700 border-amber-200",
  featured: "bg-primary/10 text-primary border-primary/20",
  home_top: "bg-primary/10 text-primary border-primary/20",
  feed: "bg-secondary/15 text-secondary-foreground border-secondary/30",
};

const labels: Record<string, string> = {
  active: "Активен",
  suspended: "Suspended",
  live: "Live",
  upcoming: "Скоро",
  past: "Прошло",
  cancelled: "Отменён",
  banned: "Бан",
  pending: "Ждёт",
  open: "Открыто",
  closed: "Закрыто",
  archived: "Архив",
  hidden: "Скрыто",
  submitted: "Отправлено",
  private: "Приватное",
  public: "Публичное",
  reviewing: "На проверке",
  resolved: "Решено",
  dismissed: "Откл.",
  free: "Free",
  paid: "Paid",
  unknown: "Неизвестно",
  plus: "Frendly+",
  afterdark: "After Dark",
  trial: "Триал",
  expired: "Истёк",
  succeeded: "Успешно",
  refunded: "Возврат",
  failed: "Ошибка",
  published: "Опубликовано",
  draft: "Черновик",
  rejected: "Отклонено",
  high: "High",
  med: "Med",
  low: "Low",
  meetup: "Встреча",
  date: "Свидание",
  subscription: "Подписка",
  "one-time": "Разовый",
  sent: "Отправлено",
  scheduled: "Запланировано",
  sending: "Идёт отправка",
  queue: "В очереди",
  approved: "Одобрено",
  needs_info: "Нужно фото",
  paused: "Пауза",
  ended: "Завершён",
  policy: "Политика",
  faq: "FAQ",
  rules: "Правила",
  onboarding: "Онбординг",
  page: "Страница",
  push: "Push",
  email: "Email",
  inapp: "In-app",
  selfie: "Селфи",
  document: "Документ",
  photo: "Фото",
  discount: "Скидка",
  credit: "Кредит",
  community: "Сообщество",
  poster: "Афиша",
  featured: "Featured",
  home_top: "Главная · топ",
  feed: "Лента",
};

export const StatusBadge = ({ status }: { status: string }) => (
  <span
    className={cn(
      "inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-semibold border",
      variants[status] || "bg-muted text-muted-foreground border-border",
    )}
  >
    {labels[status] || status}
  </span>
);
